/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Message: typeof import('./src/components/myMessage/src/Message.vue')['default']
    MessageList: typeof import('./src/components/myMessage/src/MessageList.vue')['default']
    MyButton: typeof import('./src/components/myButton/myButton.vue')['default']
    MyButton1: typeof import('./src/components/myButton/src/myButton1.vue')['default']
    MyConfirm: typeof import('./src/components/myConfirm/src/myConfirm.vue')['default']
    MyInput: typeof import('./src/components/myInput/MyInput.vue')['default']
    MyTest: typeof import('./src/components/myTest/myTest.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
